src/objects/Loop_Settings__mdt.object
<CustomObject>
    <fields>
        <fullName>Loop_Widget_Subtitle__c</fullName>
        <description>The subtitle of the Loop Widget. The text is also used in the search call to action if specified</description>
        <inlineHelpText>The subtitle of the Loop Widget. The text is also used in the search call to action if specified</inlineHelpText>
        <label>Loop Widget Subtitle</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sharable_Content_Only_Widget_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not the Sharable Content Only will be checked by default when the Loop Media widget loads</description>
        <inlineHelpText>Whether or not the Sharable Content Only will be checked by default when the Loop Media widget loads</inlineHelpText>
        <label>Sharable Content Only - Widget Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>View_All_Media_Location__c</fullName>
        <description>The location to navigate the user to when the Browse Media in Loop button is clicked</description>
        <inlineHelpText>The location to navigate the user to when the Browse Media in Loop button is clicked</inlineHelpText>
        <label>View All Media Location</label>
        <type>Url</type>
    </fields>
    <label>Loop Settings</label>
    <pluralLabel>Loop Settings</pluralLabel>
</CustomObject>

src/classes/LoopMediaWidgetController.cls
public class LoopMediaWidgetController extends LoopMediaBaseController {
    
    public String widgetSubtitle { get; set; }
    public String browseLoopLocation { get; set; }
    
    public LoopMediaWidgetController() {
        this.pageSizes = new Integer[]{ 5 };
        this.externalContentOnly = false;
        
        Loop_Settings__mdt[] loopSettings = [Select Loop_Widget_Subtitle__c, Sharable_Content_Only_Widget_Default__c, View_All_Media_Location__c From Loop_Settings__mdt Limit 1];
        
        if (loopSettings != null && loopSettings.size() > 0) {
            this.externalContentOnly = loopSettings[0].Sharable_Content_Only_Widget_Default__c;
            this.widgetSubtitle = loopSettings[0].Loop_Widget_Subtitle__c;
            this.browseLoopLocation = loopSettings[0].View_All_Media_Location__c;
        }
    }
    
    public Boolean showCta {
        get { return this.hasSearchValue == false; }
        set;
    }
}